### ISSUE TITLE
Example json-file

### ISSUE THREAD

**Issue by hakan-andersson-treetop** [ivashchenkoo/SOM_Kohonen_WpfApp#1]
Hi, and thanks for an exciting project!
Could you please include an example JSON-file to import?
Thanks!

**Comment by ivashchenkoo** [comment]
I apologize for such a late reply. I didn't notice the notification on github.
If it will be relevant, then here it is:
[mobile_eng.zip](https://github.com/ivashchenkoo/SOM_Kohonen_WpfApp/files/11824157/mobile_eng.zip)
